name: Update README with latest blog posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-latests-blog-posts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Update latest blog posts from website
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://frodeflaten.com/rss.xml"